INSERT INTO player (name) VALUES ('Roger Federer');
INSERT INTO player (name) VALUES ('Rafael Nadal');
INSERT INTO player (name) VALUES ('Novak Djokovic');
INSERT INTO player (name) VALUES ('Andy Murray');
INSERT INTO player (name) VALUES ('Daniil Medvedev');
INSERT INTO player (name) VALUES ('Stefanos Tsitsipas');
INSERT INTO player (name) VALUES ('Alexander Zverev');
INSERT INTO player (name) VALUES ('Carlos Alcaraz');
INSERT INTO player (name) VALUES ('Casper Ruud');
INSERT INTO player (name) VALUES ('Jannik Sinner');
INSERT INTO player (name) VALUES ('Dominic Thiem');
INSERT INTO player (name) VALUES ('Matteo Berrettini');
INSERT INTO player (name) VALUES ('Nick Kyrgios');
INSERT INTO player (name) VALUES ('Andrey Rublev');
INSERT INTO player (name) VALUES ('Taylor Fritz');

INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 4, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 1, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 6, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 9, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 12, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 7, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 11, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 13, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 15, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 6, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 7, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 12, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 2, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 14, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 15, 10);